language: python
python: 
  - 3.8
install:
  - pip install abstract-open-traffic-generator
script: 
  - python -m pytest tests
deploy:
  provider: pypi
  distributions: 'sdist bdist_wheel'
  skip_cleanup: true
  skip_existing: true
  username: __token__
  password: pypi-AgEIcHlwaS5vcmcCJDY4MzUyMzEyLTk5N2MtNDFlMC1hMjZjLWJiYmM3YWNlYTNiMwACUHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJhYnN0cmFjdC1vcGVuLXRyYWZmaWMtZ2VuZXJhdG9yIl19LCAidmVyc2lvbiI6IDF9AAAGIK54ksEcZ_dXe11ROf_-S-WptS1ThG-zWEYISS6jEmzZ

